// Generates src/rankings.ts - the 169 distinct starting hands ordered by
// heads-up equity against one random hand.
//
//   node --experimental-strip-types scripts/build-rankings.ts
//
// Computed with this project's own evaluator rather than copied from a chart,
// so the ordering is consistent with every other number the app produces and
// can be re-derived at any time. Spot-checked against common knowledge: aces
// first, seven-deuce offsuit last.

import { makeCard, makeRng } from '../src/cards.ts'
import { simulate } from '../src/equity.ts'

const RANKS = '23456789TJQKA'
const TRIALS = 60000

interface Ranked {
  code: string
  win: number
}

const results: Ranked[] = []
const started = Date.now()

// One representative combo per class is enough: suits are interchangeable, so
// every AKs plays identically to every other AKs.
for (let hi = 12; hi >= 0; hi--) {
  for (let lo = hi; lo >= 0; lo--) {
    const variants: Array<{ code: string; cards: number[] }> = []

    if (hi === lo) {
      variants.push({ code: `${RANKS[hi]}${RANKS[lo]}`, cards: [makeCard(hi, 0), makeCard(lo, 1)] })
    } else {
      variants.push({ code: `${RANKS[hi]}${RANKS[lo]}s`, cards: [makeCard(hi, 0), makeCard(lo, 0)] })
      variants.push({ code: `${RANKS[hi]}${RANKS[lo]}o`, cards: [makeCard(hi, 0), makeCard(lo, 1)] })
    }

    for (const { code, cards } of variants) {
      // Seed from the code so a regeneration reproduces the same ordering.
      let seed = 7
      for (const ch of code) seed = (seed * 31 + ch.charCodeAt(0)) >>> 0
      const { win, tie } = simulate({
        hole: cards,
        board: [],
        opponents: 1,
        trials: TRIALS,
        rng: makeRng(seed),
      })
      // Count half a tie as half a win, which is what a split pot is worth.
      results.push({ code, win: win + tie / 2 })
    }
  }
}

results.sort((a, b) => b.win - a.win)

const elapsed = ((Date.now() - started) / 1000).toFixed(1)
console.log(`Ranked ${results.length} starting hands in ${elapsed}s (${TRIALS.toLocaleString()} trials each)\n`)
console.log('  best 12:', results.slice(0, 12).map((r) => r.code).join(' '))
console.log('  worst 8:', results.slice(-8).map((r) => r.code).join(' '))

if (results.length !== 169) throw new Error(`expected 169 classes, got ${results.length}`)
if (results[0].code !== 'AA') throw new Error(`expected AA first, got ${results[0].code}`)
if (results[results.length - 1].code !== '72o') {
  console.warn(`  note: worst hand is ${results[results.length - 1].code}, usually 72o`)
}

const lines = [
  '// GENERATED by scripts/build-rankings.ts - do not edit by hand.',
  '//',
  '// The 169 distinct Texas Hold\'em starting hands, best first, ordered by',
  `// heads-up equity against one random hand (${TRIALS.toLocaleString()} trials each, ties`,
  '// counted as half a win). Produced with this project\'s own evaluator, so the',
  '// ordering is consistent with every other number the app reports.',
  '//',
  '// Ranking by heads-up equity is the standard proxy for hand strength. It is',
  '// not a playability ranking - suited connectors are worth more in a real game',
  '// than their raw equity suggests - but it is computable, reproducible and',
  '// good enough to define "the top N% of hands".',
  '',
  'export const HAND_RANKINGS: readonly string[] = [',
]

for (let i = 0; i < results.length; i += 8) {
  const row = results.slice(i, i + 8).map((r) => `'${r.code}'`).join(', ')
  lines.push(`  ${row},`)
}

lines.push(']')
lines.push('')
lines.push(`export const RANKING_TRIALS = ${TRIALS}`)
lines.push('')

const { writeFileSync } = await import('node:fs')
writeFileSync(new URL('../src/rankings.ts', import.meta.url), lines.join('\n'), 'utf8')
console.log('\nWrote src/rankings.ts')
