// GENERATED by scripts/build-rankings.ts - do not edit by hand.
//
// The 169 distinct Texas Hold'em starting hands, best first, ordered by
// heads-up equity against one random hand (60,000 trials each, ties
// counted as half a win). Produced with this project's own evaluator, so the
// ordering is consistent with every other number the app reports.
//
// Ranking by heads-up equity is the standard proxy for hand strength. It is
// not a playability ranking - suited connectors are worth more in a real game
// than their raw equity suggests - but it is computable, reproducible and
// good enough to define "the top N% of hands".

export const HAND_RANKINGS: readonly string[] = [
  'AA', 'KK', 'QQ', 'JJ', 'TT', '99', '88', 'AKs',
  '77', 'AQs', 'AKo', 'AJs', 'ATs', 'AQo', 'AJo', 'ATo',
  '66', 'KQs', 'A9s', 'KJs', 'A8s', 'KQo', 'KTs', 'A9o',
  'A7s', 'KJo', '55', 'A8o', 'A5s', 'KTo', 'QJs', 'A6s',
  'K9s', 'QTs', 'A4s', 'A7o', 'K8s', 'QJo', 'A3s', 'JTs',
  'A6o', 'K9o', 'A5o', 'Q9s', 'QTo', 'K7s', 'A2s', 'A4o',
  'K6s', '44', 'A3o', 'Q8s', 'K8o', 'K5s', 'Q9o', 'J9s',
  'K7o', 'JTo', 'K4s', 'A2o', 'Q7s', 'K6o', 'T9s', 'J8s',
  'K3s', 'Q6s', '33', 'J9o', 'Q8o', 'K2s', 'K5o', 'Q5s',
  'J7s', 'K4o', 'T8s', 'T9o', 'Q4s', 'Q7o', 'J8o', 'K3o',
  'Q6o', 'Q3s', 'T7s', 'K2o', 'J6s', '98s', 'J5s', '22',
  'Q2s', 'Q5o', 'T8o', 'J7o', 'Q4o', '97s', 'J4s', 'T6s',
  'Q3o', 'J3s', 'J6o', '98o', '87s', '96s', 'T7o', 'Q2o',
  'T5s', 'J2s', 'J5o', 'T4s', '86s', '97o', 'J4o', '95s',
  'T3s', 'T6o', '76s', 'T2s', '87o', 'J3o', '85s', '96o',
  'J2o', 'T5o', 'T4o', '94s', '75s', '93s', '86o', '65s',
  '95o', '84s', 'T3o', '92s', 'T2o', '76o', '74s', '85o',
  '54s', '64s', '83s', '94o', '75o', '82s', '93o', '73s',
  '65o', '53s', '84o', '63s', '92o', '43s', '74o', '54o',
  '72s', '64o', '52s', '62s', '83o', '73o', '42s', '82o',
  '53o', '63o', '32s', '43o', '72o', '52o', '62o', '42o',
  '32o',
]

export const RANKING_TRIALS = 60000
